# https://travis-ci.org/anuragkumarak95/wordnet
language: python
python:
  - 3.5
install:
  - pip install -r requirements.txt
  - pip install codecov

script: 
  - coverage run test.py

on_success:
 - codecov
