# https://travis-ci.org/anuragkumarak95/wordnet
language: python
python:
  - 3.3
  - 3.4
  - 3.5
  - 3.5-dev # 3.5 development branch
  - 3.6
  - 3.6-dev # 3.6 development branch
  - 3.7-dev # 3.7 development branch
  - nightly

install:
  - pip install -r requirements.txt
  - pip install codecov

script: 
  - coverage run test.py

after_success:
 - codecov
